# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/pb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eutils/pb.proto\"\x8b\x01\n\x03MSG\x12\x11\n\x04text\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x10\n\x03uid\x18\x03 \x01(\x03H\x02\x88\x01\x01\x12\x10\n\x03\x63id\x18\x04 \x01(\x03H\x03\x88\x01\x01\x12\x10\n\x03mid\x18\x05 \x01(\x03H\x04\x88\x01\x01\x42\x07\n\x05_textB\x07\n\x05_dataB\x06\n\x04_uidB\x06\n\x04_cidB\x06\n\x04_mid\"\x80\x01\n\x06\x42utton\x12\x1a\n\x04type\x18\x01 \x01(\x0e\x32\x0c.Button.TYPE\x12\x16\n\x03msg\x18\x02 \x01(\x0b\x32\x04.MSGH\x00\x88\x01\x01\":\n\x04TYPE\x12\x07\n\x03RAW\x10\x00\x12\x07\n\x03URL\x10\x01\x12\x08\n\x04IPFS\x10\x02\x12\x06\n\x02TG\x10\x03\x12\x06\n\x02\x42S\x10\x04\x12\x06\n\x02MS\x10\x05\x42\x06\n\x04_msgb\x06proto3')



_MSG = DESCRIPTOR.message_types_by_name['MSG']
_BUTTON = DESCRIPTOR.message_types_by_name['Button']
_BUTTON_TYPE = _BUTTON.enum_types_by_name['TYPE']
MSG = _reflection.GeneratedProtocolMessageType('MSG', (_message.Message,), {
  'DESCRIPTOR' : _MSG,
  '__module__' : 'utils.pb_pb2'
  # @@protoc_insertion_point(class_scope:MSG)
  })
_sym_db.RegisterMessage(MSG)

Button = _reflection.GeneratedProtocolMessageType('Button', (_message.Message,), {
  'DESCRIPTOR' : _BUTTON,
  '__module__' : 'utils.pb_pb2'
  # @@protoc_insertion_point(class_scope:Button)
  })
_sym_db.RegisterMessage(Button)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MSG._serialized_start=19
  _MSG._serialized_end=158
  _BUTTON._serialized_start=161
  _BUTTON._serialized_end=289
  _BUTTON_TYPE._serialized_start=223
  _BUTTON_TYPE._serialized_end=281
# @@protoc_insertion_point(module_scope)
